### ISSUE TITLE
go binary build is failed.

### ISSUE THREAD

**Issue by jenarajesh** [square/rce-agent#30]
while building client binary pb package is not finding. Hence it is failed.

**Comment by daniel-nichter** [comment]
I just tried on master and it works. What's your full build output and Go version?

**Comment by jenarajesh** [comment]
Thanks for responding.
how to download below package?
"github.com/square/rce-agent/cmd"

**Comment by daniel-nichter** [comment]
Presuming you're familiar with Go basics (if not, you'll need to read all the docs at https://golang.org/doc/), then https://github.com/square/rce-agent/tree/master/example has example code for both the server and client side packages of this repo.

**Comment by jenarajesh** [comment]
go build -o hello server.go
# command-line-arguments
./server.go:67:29: cannot use s.grpcServer (type *"google.golang.org/grpc".Server) as type *"github.com/square/rce-agent/vendor/google.golang.org/grpc".Server in argument to pb.RegisterRCEAgentServer


 go build -o hello client.go
# command-line-arguments
./client.go:118:32: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/square/rce-agent/vendor/google.golang.org/grpc".ClientConn in argument to pb.NewRCEAgentClient


 go version
go version go1.9 linux/amd64

**Comment by daniel-nichter** [comment]
That error indicates that Go isn't using the correct paths, or repos weren't put in the right paths. What's your `GOPATH` env var value? And is this repo checked out at `$GOPATH/src/github.com/square/rce-agent`?

Also, you should probably upgrade to Go v1.14.  v1.9 is very old and not really supported.

**Comment by jenarajesh** [comment]
i have two points to ask:
1. wheather this same rce-agent functionality is written in c++ language?
2. I am running rce client in one pod and server in other pod, the command "ls-tmp" request is going via envoy side car, but server is sending back response as 'grpc-message', 'command ID 643dafc359be43ee90059f6ba3794cb1 not found'

**Comment by daniel-nichter** [comment]
1. No, we've only implemented it in Go. I'm not aware of anything similar in C++.

2. That error comes from,

```go
    cmd := s.repo.Get(id.ID)
    if cmd == nil {
        return nil, notFound(id)
    }
```

It means the command (with that ID) finished and was reaped (i.e. removed from the repo of running commands). Checks the server output for these log lines:

```
	log.Printf("cmd=%s: wait", id.ID)
	defer log.Printf("cmd=%s: wait return", id.ID)
```

Did the command (with that ID) run and complete?

**Comment by jenarajesh** [comment]
Thanks for your quick response.
The issue is resolved now.

May i ask you, What is the minimum go version this rce-agent works?

**Comment by jenarajesh** [comment]
export GOROOT=/root/goold/go
export PATH=$PATH:${GOROOT}/bin
export GOPATH=/root/poc/rce
go version: go1.14.4 
we are trying to import our local go package with this rce-agent code in main.go file .
While building the binary that the imported packed package is looking under "/root/goold/go/src"
directory. As it is a local go package it is not available over /root/goold/go/src path. Hence go build failed.
error is given below: go build -o client main.go
main.go:30:5: package cli/xds is not in GOROOT (/root/goold/go/src/cli/xds)

Your quick response would help us lot. we are struggling from past two days.

**Comment by daniel-nichter** [comment]
To answer your previous question: there's no specific minimum Go version; but, generally speaking, we support the latest two Go versions, so today that'd be go1.13 and go1.14.

As to your last question/issue: this is not something we can help with since it's not a build error specific to this repo. It seems Go is not installed/set up correctly on your machine. See https://golang.org/doc/gopath_code.html#GOPATH, for example. One setup that might work for you (this is just a suggestion):

* Clone this repo to `$HOME/Development/go/src/github.com/square/rce-agent`
* Set `GOPATH=$HOME/Development/go`
* Put your code in `$HOME/Development/go/src/<your dir>`
* For code in `<your dir>` you would import this repo as `import "github.com/square/rce-agent"`

Then `go build` in `<your dir>` should work. If not, please check the [Go docs](https://golang.org/doc/) and ensure everything is set up correctly.

If there is, in fact, a bug with this repo, let us know and we can reopen this issue.
